CREATE TABLE [dbo].[FactSales] (

	[SalesOrderLineKey] int NULL, 
	[CustomerKey] int NULL, 
	[ProductKey] int NULL, 
	[StoreKey] int NULL, 
	[OrderDateKey] int NULL, 
	[CategoryKey] int NULL, 
	[OrderSourceID] varchar(8000) NULL, 
	[CustomerSourceID] varchar(8000) NULL, 
	[ProductID_OLTP] int NULL, 
	[ShippingCity] varchar(8000) NULL, 
	[PaymentMethod] varchar(8000) NULL, 
	[ShippingMethod] varchar(8000) NULL, 
	[OrderStatus] varchar(8000) NULL, 
	[CustomerSegment] varchar(8000) NULL, 
	[DeviceType] varchar(8000) NULL, 
	[ReferralSource] varchar(8000) NULL, 
	[PromotionApplied] varchar(8000) NULL, 
	[Quantity] int NULL, 
	[PricePerUnit] float NULL, 
	[DiscountPct] float NULL, 
	[SalesAmount] float NULL, 
	[DiscountAmount] float NULL, 
	[GrossAmount] float NULL, 
	[OrderTimestamp] datetime2(6) NULL, 
	[ProcessingTimestampSilver] datetime2(6) NULL, 
	[ProcessingTimestampGold] datetime2(6) NULL
);